# set the theme
theme: unidata-jekyll-theme

# this will appear in an HTML meta tag, sidebar, and perhaps elsewhere
docset_version: 2.0-draft

# this appears on the top navigation bar next to the home button
topnav_title: NetCDF User's Guide (NUG)

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: NetCDF User's Guide (NUG)

# this appears in the footer
site_topic: NetCDF User's Guide (NUG)

# if you're using Github, provide the basepath to the branch you've created for reviews. If not, leave this value blank.
github_editme_path:

# if you have google-analytics ID, put it in. if not, edit this value to blank.
# e.g. google_analytics: UA-92978945-1
google_analytics: UA-92978945-1

# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4000

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .gradle/
  - .jekyll-cache/
  - build/
  - .gitignore
  - "*gradle*"
  - "Gemfile.*"
  - README.md

# used for the Feedback link in the top navigation bar
feedback_link: "https://github.com/Unidata/netcdf/issues/new?title=NUG%20feedback"

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
collections:
  tooltips:
    output: false

# these are defaults used for the frontmatter for these file types
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      sidebar: nnug_sidebar

sidebars:
  - nnug_sidebar

# project logo (32x32), name, main landing page  (currently used in the footer)
project_logo: https://www.unidata.ucar.edu/images/logos/netcdf-32x32.png
project_name: netCDF Users Guide
project_landing_page: https://www.unidata.ucar.edu/software/netcdf/

# the description is used in the feed.xml file
description: "The NetCDF User's Guide (NUG), a language agnostic guide to the netCDF specification, data model, best practices, and base conventions."

# needed for sitemap.xml file only
# must include trailing slash, leave off the version :-)
base_docs_url: https://docs.unidata.ucar.edu/nug/